name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - hotfix/*
      - release/*
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - dev
      - feature/*
      - hotfix/*
      - release/*
      - infra/runner-toevoegen
 
jobs:
  test:
    runs-on: windows-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-windows
 
      - name: Herstel afhankelijkheden
        run: dotnet restore -r win-x64
 
      - name: Bouw de applicatie
        run: dotnet build -c Release -r win-x64 -p:TargetFramework=net8.0-windows10.0.19041.0 --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
