name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - hotfix/*
      - release/*
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - dev
      - feature/*
      - hotfix/*
      - release/*
      - infra/runner-toevoegen
 
jobs:
  test:
    runs-on: windows-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Install MAUI workloads
        run: dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build -f net8.0-android --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test -f net8.0-android --configuration Release --no-restore --no-build --verbosity normal
